### ISSUE TITLE
if a little change ,it can make it better

### ISSUE THREAD

**Issue by ChenLInXiong** [mrtazz/DoxygenToolkit.vim#1]
I use the command :Dox generate a comment for a function,looking like this
/**
 *\* @ brief test
 *
 _/
void myfunction(void)
then i use the vim comment :zM to fold all my code ,but the content of @brief can't show in the above of my function name.After test,i found that if change the /_\* to /\* (note: nothing can be follow the /_).It look like this 
/_*
 *\* @ brief test
 *
 _/
The content of @brief can be successful display in the above of the fuction. i hope you can make a small change to make it better.Just change    let g:DoxygenToolkit_startCommentTag = "/__**"  to  let g:DoxygenToolkit_startCommentTag = "/_*"  in the line 344. Thanks.

**Comment by mrtazz** [comment]
Thanks for opening an issue! I'm not sure I fully understand this. What's the advantage of changing that in the source rather than just setting it in your `.vimrc`?

**Comment by ChenLInXiong** [comment]
I don't  now how to display picture in the issue ,so maybe you don't
complete understand what i want to say,please read the doxc I follow the
email and replay.Thanks.

2016-02-23 4:26 GMT+08:00 Daniel Schauenberg notifications@github.com:

**Comment by mrtazz** [comment]
right, what I'm saying is, you should be able to just set it in your vimrc and then https://github.com/mrtazz/DoxygenToolkit.vim/blob/master/plugin/DoxygenToolkit.vim#L298 will make sure it gets respected.

**Comment by ChenLInXiong** [comment]
Oh,the code
https://github.com/mrtazz/DoxygenToolkit.vim/blob/master/plugin/DoxygenToolkit.vim#L298
is
in the LIne 344 in my DoxygenToolkit.vim,wihch i want to change is also
this.In Fact,before i open the issue .I had tried to set
let g:DoxygenToolkit_startCommentTag = "/_" ,let
g:DoxygenToolkit_startCommentBlock = "/_ " in the .vimrc and it work very
well.I want to change
https://github.com/mrtazz/DoxygenToolkit.vim/blob/master/plugin/DoxygenToolkit.vim#L299
to  let g:DoxygenToolkit_startCommentTag = "/*" just hope it can be a
default setting so it can be more convenient without set int the .vimrc.

2016-02-24 0:16 GMT+08:00 Daniel Schauenberg notifications@github.com:

**Comment by mrtazz** [comment]
I think setting this in the vimrc is a very easy and standard workflow for customization.
